#lang racket
(define counter 0)
(define lower 1)
(define upper 100)
(define (guess)
  (quotient (+ lower upper) 2))
(define (smaller)
  (set! counter (+ 1 counter))
  (displayln counter)
  (when (= counter 7) (displayln "Cheater!"))
  (set! upper (max lower (sub1 (guess))))
  (guess))
(define (bigger)
  (set! counter (+ 1 counter))
  (displayln counter)
  (when (= counter 7) (displayln "Cheater!"))
  (set! lower (min upper (add1 (guess))))
  (guess))
(define yes "Yay!")
(when (= counter 7) (displayln "Cheater!"))